### ISSUE TITLE
MultiLineString::__construct() must be of the type array, object given

### ISSUE THREAD

**Issue by bretterer** [grimzy/laravel-mysql-spatial#22] opened 2017-09-29 01:58 UTC
I am trying to use this package to store polygons in my database.  When I set up new points for each point of my polygon and use them to create a LineString to save as a Polygon on my model, I am getting an error (title of issue)

The output of Collection is shown below along with the code to generate the collection.

I have added `use SpatialTrait;` and `protected $spatialFields = ['polygon'];` to my model.

I use the generated `$polygons` variable in a relational model `save()` method.

I have also set up the migration to use your Blueprint methods, even though Laravel now supports these fields.

Code:

```php
$coords = explode(' ', $polygon);
                $tempCoords = [];
                foreach($coords as $coord) {
                    list($lat, $lon) = explode(',', $coord);
                    $tempCoords[] = new Point($lat, $lon);
                }

                $collection = new LineString($tempCoords);

                $polygons[] = new MyModel([
                    'polygon' => new Polygon($collection)
                ]);
```

Dump of $collection;

```php
Grimzy\LaravelMysqlSpatial\Types\LineString {#764
  #points: array:7 [
    0 => Grimzy\LaravelMysqlSpatial\Types\Point {#757
      #lat: 34.39
      #lng: -98.36
    }
    1 => Grimzy\LaravelMysqlSpatial\Types\Point {#758
      #lat: 34.51
      #lng: -98.46
    }
    2 => Grimzy\LaravelMysqlSpatial\Types\Point {#759
      #lat: 34.51
      #lng: -98.31
    }
    3 => Grimzy\LaravelMysqlSpatial\Types\Point {#760
      #lat: 34.4
      #lng: -98.23
    }
    4 => Grimzy\LaravelMysqlSpatial\Types\Point {#761
      #lat: 34.21
      #lng: -98.23
    }
    5 => Grimzy\LaravelMysqlSpatial\Types\Point {#762
      #lat: 34.22
      #lng: -98.37
    }
    6 => Grimzy\LaravelMysqlSpatial\Types\Point {#763
      #lat: 34.39
      #lng: -98.36
    }
  ]
}

```

**Comment by grimzy** [comment] 2017-09-30 06:26
Change:
```
'polygon' => new Polygon($collection)
```
To:
```
'polygon' => new Polygon([$collection])
```
Duplicate of #7 
_(I should document this in the readme)_

**Comment by grimzy** [comment] 2017-09-30 06:27
Duplicate of #7

**Comment by grimzy** [comment] 2017-09-30 06:32
I should document this in the readme or better, change the constructor to accept both.

**Comment by grimzy** [comment] 2017-09-30 15:04
@bretterer, you mentioned that Laravel now supports the fields defined in migrations; can you please show me how?

**Comment by Punksolid** [comment] 2017-10-17 06:34
I had the same problem. Anyways the latest version of laravel has geometry, point and other colum field types.
https://laravel.com/docs/5.5/migrations#columns

**Comment by grimzy** [comment] 2018-06-16 19:32
#32

**Closed by grimzy** 2018-06-16 19:32 UTC
Labels: duplicate, question
