### ISSUE TITLE
Declaration of Grimzy\LaravelMysqlSpatial\Schema\Blueprint::point($column)

### ISSUE THREAD

**Issue by levinhne** [grimzy/laravel-mysql-spatial#52] opened 2018-06-08 06:47 UTC
Declaration of Grimzy\LaravelMysqlSpatial\Schema\Blueprint::point($column) should be compatible with Illuminate\Database\Schema\Blueprint::point($column, $srid = NULL)

**Comment by J5Dev** [comment] 2018-06-08 11:10
This is a duplicate of #49 and already has a pull request in.

**Closed** 2018-06-16 19:22 UTC
Labels: duplicate

**Comment by andreshg112** [comment] 2018-06-27 20:14
Is there a workaround?
I can modify the source code locally but not in production.

**Comment by grimzy** [comment] 2018-06-28 16:11
@andreshg112, please update your dependency. The change was published in the latest release: `v2.1.0`.

**Comment by andreshg112** [comment] 2018-06-28 16:13
Thank you, @grimzy!

I noticed it yesterday.
